/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(pcapng_writer.h)                                          */
/* BINDTOOL_HEADER_FILE_HASH(a4379998d14b680c9b7a49eae0952c49)                   */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <bluetooth/pcapng_writer.h>
// pydoc.h is automatically generated in the build directory
#include <pcapng_writer_pydoc.h>

void bind_pcapng_writer(py::module& m)
{

    using pcapng_writer = ::gr::bluetooth::pcapng_writer;


    py::class_<pcapng_writer, std::shared_ptr<pcapng_writer>>(m, "pcapng_writer", D(pcapng_writer))

        .def(py::init(&pcapng_writer::make),
             py::arg("filename"),
             D(pcapng_writer, make))


        
        .def("init",&pcapng_writer::init,       
            D(pcapng_writer,init)
        )


        
        .def("is_enabled",&pcapng_writer::is_enabled,       
            D(pcapng_writer,is_enabled)
        )


        
        .def("write_bredr_packet",&pcapng_writer::write_bredr_packet,       
            py::arg("pkt"),
            py::arg("pn"),
            py::arg("timestamp_ns"),
            py::arg("signal_power"),
            py::arg("noise_power"),
            D(pcapng_writer,write_bredr_packet)
        )
        

        
        .def("btbb_record_bdaddr_info",&pcapng_writer::btbb_record_bdaddr_info,       
            py::arg("pn"),
            py::arg("pkt"),
            D(pcapng_writer,btbb_record_bdaddr_info)
        )


        
        .def("btbb_record_clk_info",&pcapng_writer::btbb_record_clk_info,       
            py::arg("pn"),
            py::arg("pkt"),
            py::arg("timestamp_ns"),
            D(pcapng_writer,btbb_record_clk_info)
        )


        
        .def("write_le_packet",&pcapng_writer::write_le_packet,       
            py::arg("pkt"),
            py::arg("timestamp_ns"),
            py::arg("signal_power"),
            py::arg("noise_power"),
            D(pcapng_writer,write_le_packet)
        )


        
        .def("le_record_connect_req",&pcapng_writer::le_record_connect_req,       
            py::arg("pkt"),
            py::arg("timestamp_ns"),
            D(pcapng_writer,le_record_connect_req)
        )


        
        .def("close",&pcapng_writer::close,       
            D(pcapng_writer,close)
        )

        ;
}
